kind: pipeline
name: WebCI

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: test
  image: node:12
  commands: 
  - npm install
  - npm run test
  - npm run test:cov
  - npm run test:e2e

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token


- name: publish
  image: docker:dind
  environment:
    DRONE_TAG: 
    DOCKER_USER:
      from_secret: docker_user
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - env
  - echo ${DRONE_BUILD_NUMBER}
  - docker login mobile20dockerhub.azurecr.cn -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build -t mobile20dockerhub.azurecr.cn/training-bff-web:${DRONE_BUILD_NUMBER} .
  - docker push mobile20dockerhub.azurecr.cn/training-bff-web:${DRONE_BUILD_NUMBER}

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_user
    password: 
      from_secret: ssh_password
    port: 22
    script:
      - docker service update --image mobile20dockerhub.azurecr.cn/training-bff-web:${DRONE_BUILD_NUMBER} trainning-web

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

- name: cache
  host: 
    path: /tmp/cache