kind: pipeline
name: WebCI





steps:
- name: publish
  image: docker:dind
  environment:
    DOCKER_USER:
      from_secret: docker_user
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - echo $DRONE_TAG
  - docker login mobile20dockerhub.azurecr.cn -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build -t mobile20dockerhub.azurecr.cn/training-bff-web:$DRONE_TAG .
  - docker push mobile20dockerhub.azurecr.cn/training-bff-web:$DRONE_TAG


- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: 
      from_secret: ssh_user
    password: 
      from_secret: ssh_password
    port: 22
    script:
      - docker service update --image mobile20dockerhub.azurecr.cn/training-bff-web:$DRONE_TAG trainning-web


  


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

